### ISSUE TITLE
Not working on latest Android Studio build

### ISSUE THREAD

**Issue by Tgo1014** [wQuasar/Codeowners-Lens#2]
It doesn't show on the marketplace plugins list. If I try to manually install the zip this is shown:

![](https://i.imgur.com/E0vr8gC.png)

Here's my AS info:

```Android Studio Ladybug | 2024.2.1 Nightly 2024-08-26
Build #AI-242.20224.300.2421.12275525, built on August 26, 2024
Runtime version: 21.0.3+-77717980-b509.4 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.4.1
```

Thanks!

**Comment by wQuasar** [comment]
Hello @Tgo1014. Thanks for reporting this. I've addressed this issue in the latest build. Version "0.6.2" is now available in the marketplace.

**Comment by Tgo1014** [comment]
Thanks @wQuasar!
